-- 사업자·회계 탭용 테이블 생성 스크립트
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists business_entities (
  id bigint generated by default as identity primary key,
  entity_name text not null,
  channels text,
  reg_no text,
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists accounting_notes (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  content text,
  updated_at timestamptz not null default now()
);

alter table business_entities enable row level security;
alter table accounting_notes enable row level security;

drop policy if exists "authenticated_all_business_entities" on business_entities;
create policy "authenticated_all_business_entities" on business_entities
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "authenticated_all_accounting_notes" on accounting_notes;
create policy "authenticated_all_accounting_notes" on accounting_notes
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
