-- 전휘원 대리의 "데일리 발생 여부 체크" 탭을 위한 새 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 이 파일 내용을 실행하세요.
--
-- 8개 고정 항목(item_key)에 대해 하루 1행씩 저장합니다. 항목 자체의 이름/설명은
-- index.html의 OCCURRENCE_CHECK_ITEMS 상수에 고정돼 있고, 이 테이블에는 "오늘 이
-- 항목이 발생했는지" 같은 하루 단위 상태만 저장합니다.
--
-- occurrence: '해당없음' | '발생'  (기본값 '해당없음' — 매일 새로 생성될 때의 초기값)
-- status: '해당없음' | '발생' | '진행중' | '담당자완료' | '파트장확인완료' | '지연'
--         (occurrence/체크박스 변경 시 자동으로 갱신되고, 필요하면 수동으로도 바꿀 수 있음)

create table if not exists daily_occurrence_checks (
  id bigint generated by default as identity primary key,
  assignee text not null,
  item_key text not null,
  check_date date not null,
  occurrence text not null default '해당없음',
  staff_done boolean not null default false,
  lead_done boolean not null default false,
  status text not null default '해당없음',
  memo text,
  created_at timestamptz not null default now(),
  unique (assignee, item_key, check_date)
);
