-- 공동구매 정산 자동화 — 공구별 "옵션 수수료율" 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
-- 여러 번 실행해도 안전합니다 (if not exists).
--
-- 왜 필요한가:
--   공구 주문 RAW 엑셀에는 "판매처 옵션"과 "판매가"만 있고 수수료율이 없습니다.
--   지금까지는 공구마다 엑셀에 "공구가" 시트를 손으로 만들어 붙였는데,
--   그 표를 여기에 한 번 저장해 두면 다음 정산부터 그대로 다시 씁니다.
--   groupbuy_schedule.commission_rate 는 공구 하나에 요율 하나뿐이라
--   옵션마다 20% / 25% / 30% 로 갈리는 실제 계약을 담지 못합니다.
--
--   · campaign       : 공구명. RAW 의 "판매처 상품명" 과 같은 값을 쓰면 찾기 쉽습니다.
--                      (예: 코드니처 X  로라도라홈 공동구매)
--   · partner        : 정산 대상 업체/인플루언서 이름. 정산서 머리글에 찍힙니다.
--   · option_name    : 화면과 정산서에 보여 줄 옵션명 (사람이 읽는 이름)
--   · option_key     : RAW 의 옵션명과 맞춰 보는 비교용 키.
--                      "옵션=" 접두사를 떼고 공백·괄호·기호를 없앤 값이며 화면이 자동으로 넣습니다.
--   · unit_price     : 공구판매가 (검증용. 계산은 RAW 의 판매가를 씁니다)
--   · commission_rate: 수수료율. 0.25 = 25%

create table if not exists groupbuy_commission_rates (
  id bigint generated by default as identity primary key,
  campaign text not null,
  partner text,
  option_name text not null,
  option_key text not null,
  unit_price numeric,
  commission_rate numeric not null,
  created_at timestamptz not null default now(),
  -- 같은 공구 안에서 같은 옵션이 두 번 등록되면 어느 요율을 쓸지 알 수 없으므로 막습니다.
  unique (campaign, option_key)
);

create index if not exists groupbuy_commission_rates_campaign_idx
  on groupbuy_commission_rates (campaign);

alter table groupbuy_commission_rates enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_commission_rates' and policyname = 'public read access') then
    create policy "public read access" on groupbuy_commission_rates for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_commission_rates' and policyname = 'public insert access') then
    create policy "public insert access" on groupbuy_commission_rates for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_commission_rates' and policyname = 'public update access') then
    create policy "public update access" on groupbuy_commission_rates for update using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_commission_rates' and policyname = 'public delete access') then
    create policy "public delete access" on groupbuy_commission_rates for delete using (true);
  end if;
end $$;

-- 확인 — 아래가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'groupbuy_commission_rates';
