-- 공구 주문줄 적재 표 — 매출DB 를 올릴 때마다 공구 주문만 골라 쌓아 둡니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
-- 여러 번 실행해도 안전합니다 (if not exists).
--
-- 왜 필요한가:
--   지금은 정산할 때마다 주문 파일을 다시 받아 올려야 합니다. 그런데 그 파일(매출DB)은
--   이미 매일 보고 계신 것이라, 올릴 때 공구 주문줄만 여기에 쌓아 두면 정산 시점에
--   파일이 필요 없습니다. 진행 중인 공구의 매출도 바로 볼 수 있습니다.
--
--   sales_transactions 는 건드리지 않습니다. 그 표에는 캠페인(어느 인플루언서 공구인지)과
--   옵션 칸이 없어 수수료를 계산할 수 없고, 매일 하시는 CSV 변환 흐름도 그대로 둡니다.
--
--   · campaign      : 주문 파일의 "판매처 상품명" (예: 코드니처 X  로라도라홈 공동구매)
--   · campaign_key  : 표기 흔들림(공백 두 칸 등)을 흡수한 비교용 키
--   · product_name  : 주문 파일의 "상품명". 기준표 요율을 값으로 찾을 때 같이 씁니다
--   · option_name   : "판매처 옵션". option_key 는 요율표와 맞춰 보는 키
--   · amount        : 판매가. 세트 구성품의 0 원 줄은 애초에 담지 않습니다
--   · cs_status     : 정상 / 배송전 전체 취소 / 배송후 전체 교환 ...
--   · line_seq      : 같은 주문·같은 옵션·같은 날 줄이 두 개일 수 있어 1,2,3.. 으로 구분합니다

create table if not exists groupbuy_order_lines (
  id bigint generated by default as identity primary key,
  campaign text not null,
  campaign_key text not null,
  order_no text not null,
  order_date date not null,
  vendor text,
  product_name text,
  option_name text not null,
  option_key text not null,
  qty numeric not null default 1,
  amount numeric not null,
  cs_status text,
  updated_at timestamptz not null default now(),
  line_seq integer not null default 1,
  -- 같은 파일을 다시 올려도 줄이 늘지 않게 막습니다. 취소로 바뀐 건은 덮어써집니다.
  unique (order_no, option_key, order_date, line_seq)
);

create index if not exists groupbuy_order_lines_campaign_idx
  on groupbuy_order_lines (campaign_key, order_date);

alter table groupbuy_order_lines enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_order_lines' and policyname = 'public read access') then
    create policy "public read access" on groupbuy_order_lines for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_order_lines' and policyname = 'public insert access') then
    create policy "public insert access" on groupbuy_order_lines for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_order_lines' and policyname = 'public update access') then
    create policy "public update access" on groupbuy_order_lines for update using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'groupbuy_order_lines' and policyname = 'public delete access') then
    create policy "public delete access" on groupbuy_order_lines for delete using (true);
  end if;
end $$;

-- 확인 — 아래가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'groupbuy_order_lines';
