-- 전휘원 대리의 "공동구매 발주서 취합 후 전달(w/scm)" 업무에서
-- 오늘 진행 중인 공구를 건별로 체크하기 위한 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 이 파일 내용을 실행하세요.
--
-- 하루에 공구가 여러 건 잡히면 각각 따로 체크할 수 있어야 하므로,
-- (담당자, 공구 id, 날짜) 조합마다 1행씩 저장합니다.
-- 공구 자체의 정보(브랜드·인플루언서·기간 등)는 groupbuy_schedule에 있고,
-- 이 테이블에는 "오늘 이 공구의 발주서를 취합했는지"만 저장합니다.
--
-- groupbuy_id는 groupbuy_schedule.id(text)와 같은 값입니다. 공구 일정은 외부
-- 동기화로 지워졌다 다시 생길 수 있어 외래키는 걸지 않습니다.

create table if not exists groupbuy_order_checks (
  id bigint generated by default as identity primary key,
  assignee text not null,
  groupbuy_id text not null,
  check_date date not null,
  checked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (assignee, groupbuy_id, check_date)
);

create index if not exists groupbuy_order_checks_lookup
  on groupbuy_order_checks (assignee, check_date);
