-- 전휘원 할일 관리 화면 맨 위에 붙는 "긴급 메모지" 저장용 표입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 업무별 코멘트(team_task_comments)와는 쓰임이 다릅니다.
--   · 코멘트   : 특정 업무에 묶이고, 업무목적 패널을 열어야 보입니다.
--   · 긴급 메모 : 업무와 상관없이 "급히 알아봐야 할 것"을 화면 맨 위에 띄웁니다.
--                날짜와 무관하게 지울 때까지 계속 보입니다.
--
-- 지우면 행이 사라집니다(보관하지 않습니다). 남겨둘 필요가 생기면 그때
-- deleted_at 같은 칸을 추가하는 쪽이 낫습니다.

create table if not exists jw_urgent_notes (
  id bigint generated by default as identity primary key,
  body text not null,
  -- 누가 썼는지 화면에 표시하려고 남깁니다. 로그인이 없어 강제되지는 않습니다.
  author text not null default '대표',
  created_at timestamptz not null default now()
);

-- 최근에 쓴 것이 위로 오게 정렬할 때 씁니다.
create index if not exists jw_urgent_notes_created_idx
  on jw_urgent_notes (created_at desc);

alter table jw_urgent_notes enable row level security;

drop policy if exists "public read access" on jw_urgent_notes;
drop policy if exists "public insert access" on jw_urgent_notes;
drop policy if exists "public update access" on jw_urgent_notes;
drop policy if exists "public delete access" on jw_urgent_notes;

create policy "public read access"   on jw_urgent_notes for select using (true);
create policy "public insert access" on jw_urgent_notes for insert with check (true);
create policy "public update access" on jw_urgent_notes for update using (true);
create policy "public delete access" on jw_urgent_notes for delete using (true);

-- 확인 — 아래 결과가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'jw_urgent_notes';
