-- "신제품 광고세팅" 옆 런칭 건수 배지를 위한 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 이 파일 내용을 실행하세요.
--
-- 다우게시판에 "런칭" 글이 몇 건 올라왔는지를 담당자가 직접 눌러 기록합니다.
-- (다우오피스 OpenAPI에 게시판 조회 기능이 없어 자동 수집이 불가능해, 수동 입력 방식으로 둡니다)
--
-- 오전/오후 필수업무와 마찬가지로 하루 단위라, (담당자, 날짜)당 1행만 둡니다.
-- 다음 날이 되면 행이 새로 생기므로 배지도 0에서 다시 시작합니다.

create table if not exists launch_post_counts (
  id bigint generated by default as identity primary key,
  assignee text not null,
  check_date date not null,
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (assignee, check_date)
);

create index if not exists launch_post_counts_lookup
  on launch_post_counts (assignee, check_date);
