-- 외부몰 판매가 관리 테이블 — 몰(채널)별 상품 판매가를 등록/조회합니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists mall_product_prices (
  id bigint generated by default as identity primary key,
  mall text not null,
  product_name text not null,
  price numeric,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table mall_product_prices enable row level security;

create policy "public read access" on mall_product_prices for select using (true);
create policy "public insert access" on mall_product_prices for insert with check (true);
create policy "public update access" on mall_product_prices for update using (true);
create policy "public delete access" on mall_product_prices for delete using (true);
