-- 자사몰 매일 검수를 위한 표 3개입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 대시보드(브라우저)는 자사몰을 매일 돌며 읽을 수 없습니다(다른 도메인 + 정기 실행).
-- 그래서 매일 한 번 자사몰을 읽어 그 결과를 아래 표에 넣어두고, 대시보드는 이 표만 봅니다.
--   · mall_sites        : 검수 대상 자사몰 목록 (여기에 몰을 등록해 두면 매일 자동으로 돕니다)
--   · mall_hidden_links : 공개되면 안 되는 히든링크 목록 (공구·제휴 전용 상품 등)
--   · mall_audits       : 하루치 검수 결과 — 몰 하나당 한 줄씩 쌓입니다
--
-- 검수할 때마다 한 줄씩 쌓이고, 화면은 몰별 가장 최근 줄만 씁니다.


-- ── 1. 검수 대상 자사몰 목록 ──────────────────────────────────────────────
-- 몰을 추가하고 싶으면 이 표에 한 줄만 넣으면 됩니다. 코드 수정이 필요 없습니다.
--   · platform    : 'cafe24' | 'sixshop' | 'imweb' | 'shopify' | 'etc' (읽는 방식이 조금씩 달라서 구분합니다)
--   · list_url    : 전체 상품을 볼 수 있는 공개 목록 주소 (비워두면 sitemap 으로 대신합니다)
--   · sitemap_url : 비워두면 {url}/sitemap.xml 로 자동 추정합니다
--   · is_active   : false 로 바꾸면 검수에서 잠시 제외됩니다 (줄을 지우지 않아도 됩니다)
create table if not exists mall_sites (
  id bigint generated by default as identity primary key,
  brand text not null,
  url text not null,
  platform text not null default 'etc',
  list_url text,
  sitemap_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  memo text,
  created_at timestamptz not null default now(),
  unique (brand)
);


-- ── 2. 공개되면 안 되는 히든링크 목록 ─────────────────────────────────────
-- 공동구매·제휴 전용처럼 "링크를 아는 사람만" 들어와야 하는 상품을 여기에 등록해 둡니다.
-- 매일 검수하면서 이 상품들이 공개 목록(카테고리·사이트맵)에 떠 있는지 확인합니다.
--   · product_code : 몰에서 쓰는 상품 번호/코드 (있으면 이걸로 대조하고, 없으면 url 로 대조합니다)
create table if not exists mall_hidden_links (
  id bigint generated by default as identity primary key,
  brand text not null,
  product_code text,
  product_name text,
  url text not null,
  memo text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  -- 같은 몰의 같은 상품이 두 번 들어가지 않게 막습니다.
  -- (이 파일이나 seed 파일을 여러 번 실행해도 안전합니다)
  unique (brand, product_code)
);

create index if not exists mall_hidden_links_brand_idx
  on mall_hidden_links (brand);


-- ── 3. 하루치 검수 결과 ───────────────────────────────────────────────────
--   · product_count   : 이번에 읽은 공개 상품 수
--   · new_count       : 지난 검수 대비 새로 생긴 상품 수  → "신규 상품" 알림에 씁니다
--   · exposed_count   : 히든링크인데 공개 목록에 떠 있는 상품 수  → 빨간 배지에 씁니다
--   · new_products    : 신규 상품 목록 [{상품코드, 상품명, url, 가격}]
--   · exposed_hidden  : 노출된 히든링크 목록 [{상품코드, 상품명, url, 발견위치}]
--   · products        : 이번에 읽은 전체 공개 상품 (다음 검수 때 "신규"를 가려내는 기준이 됩니다)
--   · status          : 'ok' | 'warn' | 'error'  — error 면 몰을 못 읽은 것이라 사람이 봐야 합니다
create table if not exists mall_audits (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  check_date date not null default (now() at time zone 'Asia/Seoul')::date,
  brand text not null,
  url text,
  status text not null default 'ok',
  product_count integer not null default 0,
  new_count integer not null default 0,
  exposed_count integer not null default 0,
  new_products jsonb not null default '[]'::jsonb,
  exposed_hidden jsonb not null default '[]'::jsonb,
  products jsonb not null default '[]'::jsonb,
  error_message text,
  notified boolean not null default false
);

create index if not exists mall_audits_brand_checked_idx
  on mall_audits (brand, checked_at desc);
create index if not exists mall_audits_checked_idx
  on mall_audits (checked_at desc);


-- ── 권한 (기존 표들과 같은 방식) ──────────────────────────────────────────
alter table mall_sites        enable row level security;
alter table mall_hidden_links enable row level security;
alter table mall_audits       enable row level security;

do $$
declare t text;
begin
  foreach t in array array['mall_sites', 'mall_hidden_links', 'mall_audits'] loop
    execute format('drop policy if exists "public read access" on %I', t);
    execute format('drop policy if exists "public insert access" on %I', t);
    execute format('drop policy if exists "public update access" on %I', t);
    execute format('drop policy if exists "public delete access" on %I', t);
    execute format('create policy "public read access"   on %I for select using (true)', t);
    execute format('create policy "public insert access" on %I for insert with check (true)', t);
    execute format('create policy "public update access" on %I for update using (true)', t);
    execute format('create policy "public delete access" on %I for delete using (true)', t);
  end loop;
end $$;


-- 확인 — 아래 결과가 3줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public'
  and table_name in ('mall_sites', 'mall_hidden_links', 'mall_audits')
order by table_name;
