-- 외부몰 행사(직접 입력) 테이블 — 영업팀 워크스페이스 "일정" 화면용
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists mall_events (
  id bigint generated by default as identity primary key,
  mall text,
  title text not null,
  start_date date not null,
  end_date date not null,
  memo text,
  created_at timestamptz not null default now()
);

alter table mall_events enable row level security;

create policy "public read access" on mall_events for select using (true);
create policy "public insert access" on mall_events for insert with check (true);
create policy "public update access" on mall_events for update using (true);
create policy "public delete access" on mall_events for delete using (true);
