-- 외부몰 등록 현황을 담는 표입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 대시보드(브라우저)는 사방넷에 직접 접속할 수 없습니다(로그인 + 다른 도메인).
-- 그래서 사방넷 화면을 읽어 그 결과를 이 표에 한 줄로 넣어두고, 대시보드는 이 표만 봅니다.
--   · products      : 사방넷 상품 목록 [{품번, 상품명, 브랜드, 상태}]
--   · registrations : 어떤 품번이 어떤 몰에 등록됐는지 [{품번, 몰, 상태, 등록일}]
--   · malls         : 등록 대상 몰 이름 목록
--
-- 읽어올 때마다 한 줄씩 쌓이고, 화면은 가장 최근 줄만 씁니다.

create table if not exists mall_registrations (
  id bigint generated by default as identity primary key,
  synced_at timestamptz not null default now(),
  source text not null default '사방넷',
  product_count integer,
  registration_count integer,
  malls jsonb,
  products jsonb,
  registrations jsonb
);

create index if not exists mall_registrations_synced_idx
  on mall_registrations (synced_at desc);

alter table mall_registrations enable row level security;

drop policy if exists "public read access" on mall_registrations;
drop policy if exists "public insert access" on mall_registrations;
drop policy if exists "public update access" on mall_registrations;

create policy "public read access" on mall_registrations for select using (true);
create policy "public insert access" on mall_registrations for insert with check (true);
create policy "public update access" on mall_registrations for update using (true);

-- 확인 — 아래 결과가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'mall_registrations';
