-- 외부몰 판매가 — 외부몰에 실제로 올라가 있는 가격을 상품(품번) × 몰 한 줄씩 담습니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 예전에 만들어 두고 쓰지 않던 mall_product_prices 표에 칸을 더해서 씁니다.
--   · product_code      : 사방넷 품번 (외부몰 등록 현황과 같은 번호)
--   · brand             : 브랜드
--   · price             : 몰에서 지금 팔리는 가격(할인 적용가)
--   · list_price        : 몰에 표시된 정가(할인 전 가격, 없으면 비움)
--   · mall_product_code : 그 몰의 상품번호
--   · url               : 그 몰의 상품 페이지
--   · checked_at        : 가격을 읽어온 시각
-- 같은 품번·몰은 한 줄만 남고, 다시 읽어오면 그 줄이 새 가격으로 바뀝니다.

create table if not exists mall_product_prices (
  id bigint generated by default as identity primary key,
  mall text not null,
  product_name text not null,
  price numeric,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table mall_product_prices add column if not exists product_code text;
alter table mall_product_prices add column if not exists brand text;
alter table mall_product_prices add column if not exists list_price numeric;
alter table mall_product_prices add column if not exists mall_product_code text;
alter table mall_product_prices add column if not exists url text;
alter table mall_product_prices add column if not exists source text default '사방넷';
alter table mall_product_prices add column if not exists checked_at timestamptz default now();

create unique index if not exists mall_product_prices_code_mall_idx
  on mall_product_prices (product_code, mall);

alter table mall_product_prices enable row level security;

drop policy if exists "public read access" on mall_product_prices;
drop policy if exists "public insert access" on mall_product_prices;
drop policy if exists "public update access" on mall_product_prices;
drop policy if exists "public delete access" on mall_product_prices;

create policy "public read access" on mall_product_prices for select using (true);
create policy "public insert access" on mall_product_prices for insert with check (true);
create policy "public update access" on mall_product_prices for update using (true);
create policy "public delete access" on mall_product_prices for delete using (true);

-- 확인 — 아래 결과에 product_code, list_price, checked_at 이 보이면 성공입니다.
select column_name as "칸 이름"
from information_schema.columns
where table_schema = 'public' and table_name = 'mall_product_prices'
order by ordinal_position;
