-- 거래처 운영현황 "견적서 관리" 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
-- 여러 번 실행해도 안전합니다 (if not exists).
--
--  · partner_quotes       : 견적서 한 장 (머리글 · 합계 · 상태)
--  · partner_quote_items  : 그 견적서 안의 품목 줄 (도번 · 품명 · 개수 · 단가 · 금액)
--
-- 금액 규칙은 "진행 중 거래 건 관리"와 같습니다.
--   · 과세  : 단가·금액은 부가세가 포함된 값. 공급가 = 합계 ÷ 1.1, 세액 = 나머지
--   · 영세율: 합계 전체가 공급가, 세액은 0

create table if not exists partner_quotes (
  id bigint generated by default as identity primary key,
  quote_no text not null,
  quote_date date not null default current_date,
  partner_id bigint references partners(id) on delete set null,
  -- 거래처가 나중에 지워져도 견적서에 찍힌 이름은 남아야 하므로 이름을 그대로 한 벌 보관합니다.
  partner_name text not null,
  deal_id bigint references partner_deals(id) on delete set null,
  category text not null default 'B2B 직납',
  -- "OOO에 대하여 아래와 같이 견적합니다" 의 OOO 자리
  subject text,
  tax_type text not null default '과세',          -- 과세 / 영세율
  total_amount numeric not null default 0,        -- 합계금액 (과세면 부가세 포함)
  supply_amount numeric,                          -- 공급가
  tax_amount numeric,                             -- 세액
  note text,                                      -- 적요
  issuer_name text,                               -- 담당자
  issuer_phone text,                              -- 전화번호
  status text not null default '초안',            -- 초안 / 발행 / 수주 / 취소
  source text not null default '수동',            -- 수동 / 자동 / 히스토리
  created_at timestamptz not null default now()
);

create table if not exists partner_quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references partner_quotes(id) on delete cascade,
  line_no integer not null default 1,             -- 도번
  product_name text not null,                     -- 품명
  -- 품명에서 띄어쓰기·괄호 등을 뗀 비교용 이름. 같은 상품이 다시 들어왔는지 찾을 때 씁니다.
  product_key text,
  qty numeric,                                    -- 개수
  spec text,                                      -- 항목명 (카톤사이즈 등 자유 기재)
  unit_price numeric,                             -- 단가
  amount numeric,                                 -- 금액 (개수 × 단가)
  memo text
);

-- 같은 상품의 과거 단가를 찾을 때 쓰는 인덱스
create index if not exists partner_quote_items_product_key_idx on partner_quote_items (product_key);
create index if not exists partner_quote_items_quote_id_idx on partner_quote_items (quote_id);
create index if not exists partner_quotes_date_idx on partner_quotes (quote_date desc);

alter table partner_quotes enable row level security;
alter table partner_quote_items enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'partner_quotes' and policyname = 'public read access') then
    create policy "public read access" on partner_quotes for select using (true);
    create policy "public insert access" on partner_quotes for insert with check (true);
    create policy "public update access" on partner_quotes for update using (true);
    create policy "public delete access" on partner_quotes for delete using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'partner_quote_items' and policyname = 'public read access') then
    create policy "public read access" on partner_quote_items for select using (true);
    create policy "public insert access" on partner_quote_items for insert with check (true);
    create policy "public update access" on partner_quote_items for update using (true);
    create policy "public delete access" on partner_quote_items for delete using (true);
  end if;
end $$;

-- 확인 — 아래 결과가 2줄 나오면 성공입니다.
select table_name as "만들어진 표", count(*) as "칸 수"
from information_schema.columns
where table_schema = 'public' and table_name in ('partner_quotes', 'partner_quote_items')
group by table_name
order by table_name;
