-- 세금계산서 발행 요청 자동화 — 거래처 마스터 보강
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
-- 여러 번 실행해도 안전합니다.
--
-- 월별 "세금계산서 발행 요청서.xlsx" 를 자동으로 만들려면 견적서에 없는 값이 필요합니다.
--   · 사업자등록번호 · E-mail 주소 → 지금 거래처 33곳 전부 비어 있습니다
--   · 판매처(세금계산서를 받는 법인명) → 거래처명과 다른 경우가 있습니다
--     예) 거래처 "헤이딜러" 의 계산서는 "주식회사 피알앤디테크베이" 앞으로 나갑니다
--
-- 사내 공유 폴더의 지난 요청서 20장에서 긁어온 값을 그대로 넣습니다.

-- 0) 중복 거래처 정리
--    "YF" 는 "YF 인터네셔널" 의 잘린 이름이고, "트리플헛츠" 는 "트리플렛츠" 의 오타입니다.
--    둘 다 견적서·거래 건·수금 내역이 하나도 걸려 있지 않은 것을 확인하고 지웁니다.
--    혹시라도 그 사이에 뭔가 연결됐다면 아래 조건에 걸려 지워지지 않습니다.
delete from partners p
where p.name in ('YF', '트리플헛츠')
  and not exists (select 1 from partner_quotes   q where q.partner_id = p.id)
  and not exists (select 1 from partner_deals    d where d.partner_id = p.id)
  and not exists (select 1 from partner_payments y where y.partner_id = p.id);

-- 1) 거래처에 칸을 추가합니다.
alter table partners add column if not exists email text;
-- 세금계산서를 받는 법인명. 비어 있으면 거래처명(name)을 그대로 씁니다.
alter table partners add column if not exists invoice_name text;

-- 2) 세금계산서 수신처 마스터 — 지난 요청서에 나온 판매처 29곳입니다.
--    B2B 직납 외에 올리브영·마켓컬리 같은 채널도 들어 있어, 요청서를 손으로 채울 때
--    사업자번호·메일을 찾아보는 용도로 함께 보관합니다.
create table if not exists tax_invoice_recipients (
  id bigint generated by default as identity primary key,
  invoice_name text not null unique,   -- 판매처 (세금계산서 받는 법인)
  business_reg_no text,
  email text,
  sales_channel text,                  -- 매출처 (채널·브랜드명)
  memo text,
  created_at timestamptz not null default now()
);

alter table tax_invoice_recipients enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'tax_invoice_recipients' and policyname = 'public read access') then
    create policy "public read access" on tax_invoice_recipients for select using (true);
    create policy "public insert access" on tax_invoice_recipients for insert with check (true);
    create policy "public update access" on tax_invoice_recipients for update using (true);
    create policy "public delete access" on tax_invoice_recipients for delete using (true);
  end if;
end $$;

insert into tax_invoice_recipients (invoice_name, business_reg_no, email, sales_channel, memo)
select v.invoice_name, v.business_reg_no, v.email, v.sales_channel, v.memo
from (values
  ('올리브영',                 '556-86-00939',   'junho.lee@whyncom.co.kr',   '와이앤커머스',                    null),
  ('마켓컬리',                 '261-81-23567',   'sco07@kurlycorp.com',       '㈜컬리',                         null),
  ('주식회사 버킷플레이스',      '119-86-91245',   'dainlee@bucketplace.net',   '오프하우스',                      null),
  ('아난티코브',               '621-81-99425',   'ananticove.retail@ananti.kr', '아난티',                        '아난티는 법인이 둘이라 나눠 두었습니다'),
  ('빌라쥬드아난티',            '896-85-02328',   'alsrud5236@ananti.kr',      '아난티',                          '아난티는 법인이 둘이라 나눠 두었습니다'),
  ('옵티마웰니스뮤지엄종각약국',  '843-12-02539',   'agjhana44@naver.com',       '옵티마 웰니스 뮤지엄 종각점',      null),
  ('그린종합상사',             '271-01-03251',   'shiregold@naver.com',       null,                             null),
  ('주식회사 바인터네셔널',      '289-81-01426',   'bahkorea2@gmail.com',       '마쿠아케',                        null),
  ('요고몰',                   '516-87-01107',   'partner@glowuprizz.com',    '글로우업리즈 주식회사',            null),
  ('엠알엔(MRN)컴퍼니',         '721-48-00939',   'jkh197303@daum.net',        null,                             null),
  ('주식회사 피알앤디테크베이',   '565-86-03060',   'hardy@prnd.co.kr',          '헤이딜러',                        null),
  ('주식회사 지엠',             '396-88-02867',   'accounts@gm.company',       null,                             '"지엠" 으로도 적히던 곳입니다'),
  ('오프라인 소품샵',           '681-87-02604',   'accounts@avivere.co.kr',    '아비베르',                        null),
  ('공동구매',                 '463-87-02632',   's2hcorp@naver.com',         'S2H',                            null),
  ('중랑구 보건소',            '216-83-00516',   'kimwh1015@jn.go.kr',        null,                             '메일 도메인이 jn.go.kr(전라남도)로 되어 있어 확인이 필요합니다'),
  ('올어바웃엔젠',             '110111-0943576', 'bpf914gmail.com',           null,                             '메일에 @ 가 빠져 있습니다 — 확인 후 고쳐주세요'),
  ('주식회사 옵티젠',           '303-86-00387',   'optigen77@gmail.com',       null,                             null),
  ('정감',                     '534-05-03015',   '2024jeonggam@gmail.com',    null,                             null),
  ('오후살림',                 '521-69-00241',   'ohu.suggest@gmail.com',     null,                             null),
  ('주식회사 셀러브리티',        '644-87-02639',   'luckqii22@naver.com',       null,                             '"셀러브리티" 로도 적히던 곳입니다'),
  ('제이허브',                 '209-30-43700',   'jeyjeycompany@naver.com',   null,                             null),
  ('브랜루트',                 '726-69-00623',   'famouslkm@kakao.com',       null,                             null),
  ('까르멘 기프트',             '252-42-01084',   'sscarmen@hanmail.net',      null,                             null),
  ('주식회사 브이벨',           '887-86-01486',   'vvelcr@v-vel.co.kr',        null,                             null),
  ('KR글로벌',                 '234-42-00471',   'krglobal02@gmail.com',      null,                             null),
  ('주식회사 다올스토리',        '741-87-02605',   'ymmj0340@naver.com',        '남양유업',                        null),
  ('제이엘',                   '669-27-01936',   'jlbiz@kaka.com',            null,                             '메일이 kaka.com 으로 되어 있습니다 — kakao.com 인지 확인이 필요합니다'),
  ('트리플렛츠',               '527-02-01435',   'account2019@naver.com',     '유라시아인터내셔날',              null)
) as v(invoice_name, business_reg_no, email, sales_channel, memo)
where not exists (select 1 from tax_invoice_recipients r where r.invoice_name = v.invoice_name);

-- 3) 우리 거래처 중 위 마스터와 이어지는 10곳에 값을 채웁니다.
--    (invoice_name 이 거래처명과 같으면 굳이 넣지 않고 비워 둡니다)
update partners p
set business_reg_no = v.business_reg_no,
    email           = v.email,
    invoice_name    = case when v.invoice_name = p.name then null else v.invoice_name end
from (values
  ('그린종합상사',           '그린종합상사',              '271-01-03251', 'shiregold@naver.com'),
  ('까르멘기프트',           '까르멘 기프트',             '252-42-01084', 'sscarmen@hanmail.net'),
  ('남양유업',               '주식회사 다올스토리',        '741-87-02605', 'ymmj0340@naver.com'),
  ('엠알엔컴퍼니',           '엠알엔(MRN)컴퍼니',         '721-48-00939', 'jkh197303@daum.net'),
  ('옵티젠',                 '주식회사 옵티젠',           '303-86-00387', 'optigen77@gmail.com'),
  ('중랑구 보건소',          '중랑구 보건소',             '216-83-00516', 'kimwh1015@jn.go.kr'),
  ('트리플렛츠',             '트리플렛츠',                '527-02-01435', 'account2019@naver.com'),
  ('헤이딜러',               '주식회사 피알앤디테크베이',   '565-86-03060', 'hardy@prnd.co.kr'),
  ('브이벨',                 '주식회사 브이벨',           '887-86-01486', 'vvelcr@v-vel.co.kr'),
  ('제이허브',               '제이허브',                  '209-30-43700', 'jeyjeycompany@naver.com')
) as v(partner_name, invoice_name, business_reg_no, email)
where p.name = v.partner_name
  and p.business_reg_no is null;   -- 이미 채워 둔 값은 덮어쓰지 않습니다

-- 확인 1 — 사업자번호가 채워진 거래처 10곳이 나오면 성공입니다.
select name as "거래처", coalesce(invoice_name, name) as "판매처(계산서 받는 곳)",
       business_reg_no as "사업자등록번호", email as "E-mail"
from partners
where business_reg_no is not null
order by name;

-- 확인 2 — 아직 사업자번호가 없는 거래처입니다. 계산서를 끊으려면 채워야 합니다.
select name as "사업자번호 없는 거래처"
from partners
where business_reg_no is null
order by name;
