-- 거래처 운영현황(B2B 거래처 + 수금/지급 관리) 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists partners (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default '공급업체',
  contact_name text,
  contact_phone text,
  business_reg_no text,
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists partner_payments (
  id bigint generated by default as identity primary key,
  partner_id bigint references partners(id) on delete cascade,
  direction text not null default '수금',
  title text,
  amount numeric,
  due_date date,
  status text not null default '예정',
  memo text,
  created_at timestamptz not null default now()
);

alter table partners enable row level security;
alter table partner_payments enable row level security;

create policy "public read access" on partners for select using (true);
create policy "public insert access" on partners for insert with check (true);
create policy "public update access" on partners for update using (true);
create policy "public delete access" on partners for delete using (true);

create policy "public read access" on partner_payments for select using (true);
create policy "public insert access" on partner_payments for insert with check (true);
create policy "public update access" on partner_payments for update using (true);
create policy "public delete access" on partner_payments for delete using (true);
