-- 거래처 운영현황 "진행 건 관리"(B2B 직납 / 수출 / 해외펀딩 / 특판 영업 파이프라인) 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists partner_deals (
  id bigint generated by default as identity primary key,
  category text not null default 'B2B 직납',
  partner_id bigint references partners(id) on delete set null,
  title text not null,
  stage text not null default '문의 접수',
  expected_amount numeric,
  payment_terms text,
  collection_status text not null default '미발생',
  next_action text,
  due_date date,
  assignee text,
  memo text,
  created_at timestamptz not null default now()
);

alter table partner_deals enable row level security;

create policy "public read access" on partner_deals for select using (true);
create policy "public insert access" on partner_deals for insert with check (true);
create policy "public update access" on partner_deals for update using (true);
create policy "public delete access" on partner_deals for delete using (true);

-- 수금/지급 관리에서 진행 건(거래 건명)을 함께 표시하기 위한 연결 컬럼 + 실제 처리일 컬럼 추가
alter table partner_payments add column if not exists deal_id bigint references partner_deals(id) on delete set null;
alter table partner_payments add column if not exists paid_date date;

-- 거래처 목록에 국가 / 거래 상태 컬럼 추가
alter table partners add column if not exists country text;
alter table partners add column if not exists status text not null default '거래중';
