-- 상품등록 검수 결과를 담는 표입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 대시보드(브라우저)는 사방넷에 직접 접속할 수 없습니다(로그인 + 다른 도메인).
-- 그래서 사방넷 화면을 읽어 그 결과를 이 표에 넣어두고, 대시보드는 이 표만 봅니다.
--   · fail_recent : 최근 7일 등록 실패 건수  → 전휘원 할일 관리 "상품등록" 배지에 씁니다
--   · fail_total  : 조회 기간(period_days) 전체 실패 건수
--   · soldout_count / stopped_count : 사방넷 대시보드의 일시품절 · 판매중지 건수
--   · fails       : 실패 목록(상품코드·사유 등)을 그대로 담아 둡니다
--
-- 검수할 때마다 한 줄씩 쌓이고, 화면은 가장 최근 줄만 씁니다.

create table if not exists product_reg_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  source text not null default '사방넷',
  period_days integer,
  fail_recent integer not null default 0,
  fail_total integer not null default 0,
  soldout_count integer,
  stopped_count integer,
  total_products integer,
  fails jsonb
);

create index if not exists product_reg_checks_checked_idx
  on product_reg_checks (checked_at desc);

alter table product_reg_checks enable row level security;

drop policy if exists "public read access" on product_reg_checks;
drop policy if exists "public insert access" on product_reg_checks;
drop policy if exists "public update access" on product_reg_checks;

create policy "public read access" on product_reg_checks for select using (true);
create policy "public insert access" on product_reg_checks for insert with check (true);
create policy "public update access" on product_reg_checks for update using (true);

-- 확인 — 아래 결과가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'product_reg_checks';
