-- 영업팀 "재고 현황" 탭용 테이블 생성 스크립트
-- 지금은 직접 입력 방식이며, 추후 이지어드민 Open API 인증정보가 준비되면
-- 이 테이블에 서버(Vercel 서버리스 함수)가 자동으로 upsert하도록 확장할 수 있습니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists product_inventory (
  id bigint generated by default as identity primary key,
  brand text,
  product_name text not null,
  sku text,
  stock_qty integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table product_inventory enable row level security;

drop policy if exists "public read access" on product_inventory;
drop policy if exists "public insert access" on product_inventory;
drop policy if exists "public update access" on product_inventory;
drop policy if exists "public delete access" on product_inventory;

create policy "public read access" on product_inventory for select using (true);
create policy "public insert access" on product_inventory for insert with check (true);
create policy "public update access" on product_inventory for update using (true);
create policy "public delete access" on product_inventory for delete using (true);
