-- 견적서 품명 ↔ 원가 대시보드 항목 연결표
-- Supabase 프로젝트 대시보드 > SQL Editor 에 붙여넣고 Run 하세요. 여러 번 돌려도 안전합니다.
--
-- 견적서에서 쓰는 품명과 원가 대시보드(product_cost)의 상품명이 다른 경우가 많습니다.
--   견적서 "오행염주"          ↔ 원가 대시보드 "[명퉤] 길운 오행 염주 / 여자"
--   견적서 "러닝 제습 서버"     ↔ 원가 대시보드 "[라스마] 러닝 슈즈 제습 서버"
--
-- 원가 대시보드의 상품명을 직접 바꾸지 않고 연결만 기록합니다.
-- SKU손익 화면이 codenit_products 와 product_cost 를 "이름"으로 맞추고 있어서,
-- 원가 대시보드 이름을 고치면 그쪽 매칭이 끊깁니다.
-- 여기에 한 번 넣어 두면 그 뒤로는 견적서에서 원가가 자동으로 잡힙니다.

create table if not exists product_cost_aliases (
  id bigint generated by default as identity primary key,
  -- 견적서 품명에서 띄어쓰기·기호를 뗀 비교용 키 (화면의 품명 정규화와 같은 규칙)
  quote_product_key text not null unique,
  -- 어떤 품명을 이었는지 사람이 알아보기 위한 원본
  quote_product_name text not null,
  cost_product_id bigint not null references product_cost(id) on delete cascade,
  memo text,
  created_at timestamptz not null default now()
);

alter table product_cost_aliases enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'product_cost_aliases' and policyname = 'public read access') then
    create policy "public read access" on product_cost_aliases for select using (true);
    create policy "public insert access" on product_cost_aliases for insert with check (true);
    create policy "public update access" on product_cost_aliases for update using (true);
    create policy "public delete access" on product_cost_aliases for delete using (true);
  end if;
end $$;

-- 확인 — 빈 표가 만들어집니다. 연결은 화면에서 넣거나 다음 SQL로 넣습니다.
select count(*) as "연결 건수" from product_cost_aliases;
