-- 프로모션 매출 화면용 테이블 3개
-- 구글시트 "영업팀_OKR 진척도 > 이혜원_외부몰 행사 분석" 시트를 그대로 옮긴 구조입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

-- 1) 행사(기획전) 한 건 — 시트의 진행일정/판매처/기획전명/상태/기획전 전 동일기간 매출
create table if not exists promo_events (
  id bigint generated by default as identity primary key,
  mall text,                       -- 판매처 (오늘의집, 지그재그, 29CM ...)
  title text not null,             -- 기획전명
  start_date date not null,        -- 진행일정 시작
  end_date date not null,          -- 진행일정 종료
  status text not null default '시작전',  -- 시작전 / 진행중 / 종료
  baseline_sales numeric,          -- 기획전 전 동일기간 매출 (증감 계산 기준)
  memo text,
  created_at timestamptz not null default now()
);

-- 2) 행사에 붙는 참여상품 줄 — 시트의 참여상품/판매가/프로모션가/판매수량
--    할인율·품별 매출액·총 매출액·증감·증감률은 화면에서 계산하므로 저장하지 않습니다.
create table if not exists promo_event_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references promo_events(id) on delete cascade,
  product_name text not null,      -- 참여상품
  list_price numeric,              -- 판매가
  promo_price numeric,             -- 프로모션가
  qty numeric not null default 0,  -- 판매수량
  created_at timestamptz not null default now()
);

create index if not exists promo_event_items_event_id_idx on promo_event_items(event_id);

-- 3) 월 행사 목표매출 — 시트 좌측 상단의 "월 행사 목표매출"(기본 300만원)
create table if not exists promo_monthly_targets (
  month text primary key,          -- 'YYYY-MM'
  target numeric not null default 3000000,
  updated_at timestamptz not null default now()
);

alter table promo_events enable row level security;
alter table promo_event_items enable row level security;
alter table promo_monthly_targets enable row level security;

create policy "public read access" on promo_events for select using (true);
create policy "public insert access" on promo_events for insert with check (true);
create policy "public update access" on promo_events for update using (true);
create policy "public delete access" on promo_events for delete using (true);

create policy "public read access" on promo_event_items for select using (true);
create policy "public insert access" on promo_event_items for insert with check (true);
create policy "public update access" on promo_event_items for update using (true);
create policy "public delete access" on promo_event_items for delete using (true);

create policy "public read access" on promo_monthly_targets for select using (true);
create policy "public insert access" on promo_monthly_targets for insert with check (true);
create policy "public update access" on promo_monthly_targets for update using (true);
create policy "public delete access" on promo_monthly_targets for delete using (true);
