-- 정산 관리(공동구매 · 수출) 테이블 — 영업팀 워크스페이스 "프로모션" 화면용
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists settlements (
  id bigint generated by default as identity primary key,
  category text not null default '공동구매',
  partner text,
  amount numeric,
  settlement_date date,
  status text not null default '대기',
  memo text,
  created_at timestamptz not null default now()
);

alter table settlements enable row level security;

create policy "public read access" on settlements for select using (true);
create policy "public insert access" on settlements for insert with check (true);
create policy "public update access" on settlements for update using (true);
create policy "public delete access" on settlements for delete using (true);
