-- 팀관리(업무 프로세스 / 할일 관리) 대시보드용 테이블 생성 스크립트
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.
--
-- ⚠️ team_tasks 접근 권한은 "공개"입니다.
--    대시보드는 로그인 없이 publishable(anon) 키로 붙기 때문에, 예전처럼
--    auth.role() = 'authenticated' 로 걸어 두면 읽기·쓰기가 전부 막혀 화면이 텅 빕니다.
--    (운영 DB는 이미 공개로 바꿔 쓰고 있었는데 이 파일만 옛 내용으로 남아 있었습니다.
--     이 파일로 새로 세팅하면 화면이 안 뜨는 문제가 있어 실제와 맞췄습니다.)
--    외부에 열리는 주소로 쓸 일이 생기면 Supabase Auth 를 붙이고 정책을 다시 조이세요.
--
-- 여러 번 실행해도 안전합니다.

create table if not exists team_process_steps (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  step_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists team_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  assignee text,
  due_date date,
  status text not null default '할일',
  memo text,
  created_at timestamptz not null default now()
);

alter table team_process_steps enable row level security;
alter table team_tasks enable row level security;

-- team_process_steps 는 지금 화면에서 쓰지 않습니다. 쓰게 되면 아래 team_tasks 처럼 풀어주세요.
drop policy if exists "authenticated_all_team_process_steps" on team_process_steps;
create policy "authenticated_all_team_process_steps" on team_process_steps
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- 할일 관리 화면이 쓰는 표 — 공개 (위 머리말 참고)
-- 이름이 무엇이든 기존 정책은 전부 걷어냅니다. 하나씩 이름으로 지우면
-- 이름이 다를 때 아래 create 에서 "이미 있다"고 실패합니다.
do $$
declare p record;
begin
  for p in select policyname from pg_policies
           where schemaname = 'public' and tablename = 'team_tasks'
  loop
    execute format('drop policy %I on team_tasks', p.policyname);
  end loop;
end $$;

create policy "public read access"   on team_tasks for select using (true);
create policy "public insert access" on team_tasks for insert with check (true);
create policy "public update access" on team_tasks for update using (true);
create policy "public delete access" on team_tasks for delete using (true);

-- 확인 — team_tasks 에 4줄(SELECT/INSERT/UPDATE/DELETE)이 나오면 정상입니다.
select tablename as "표", policyname as "정책 이름", cmd as "동작"
from pg_policies
where schemaname = 'public' and tablename in ('team_tasks', 'team_process_steps')
order by tablename, cmd;
