-- 팀관리(업무 프로세스 / 할일 관리) 대시보드용 테이블 생성 스크립트
-- Supabase 프로젝트 대시보드 > SQL Editor 에서 실행하세요.

create table if not exists team_process_steps (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  step_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists team_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  assignee text,
  due_date date,
  status text not null default '할일',
  memo text,
  created_at timestamptz not null default now()
);

alter table team_process_steps enable row level security;
alter table team_tasks enable row level security;

create policy "authenticated_all_team_process_steps" on team_process_steps
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "authenticated_all_team_tasks" on team_tasks
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
