-- 전휘원 할일 관리 "업무목적" 패널의 댓글 · 대댓글 저장용 테이블
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 기존에는 team_task_notes 에 "파트장 코멘트" 1칸 + "담당자 답글" 1칸만 저장했는데,
-- 여러 번 주고받을 수 있도록 한 줄에 댓글 하나씩 쌓이는 구조로 바꿉니다.
--   · parent_id 가 비어 있으면  → 댓글
--   · parent_id 에 값이 있으면  → 그 댓글에 달린 대댓글
--
-- team_task_purposes(업무 목적)는 그대로 씁니다.
-- team_task_notes 는 더 이상 쓰지 않지만, 지우지 않고 그냥 둡니다.
--
-- ⚠️ SQL 편집기는 스크립트 전체를 한 트랜잭션으로 실행합니다. 중간 한 줄만 실패해도
--    앞에서 만든 테이블까지 전부 취소되므로, 여러 번 실행해도 안전하게 작성했습니다.

create table if not exists team_task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null,
  parent_id bigint,                                  -- null = 댓글, 값 있으면 대댓글
  author text not null,                              -- '파트장' | '담당자'
  body text not null,
  created_at timestamptz not null default now()
);

-- 업무별로 시간순 조회가 잦아서 인덱스를 둡니다.
create index if not exists team_task_comments_task_idx
  on team_task_comments (task_id, created_at);

alter table team_task_comments enable row level security;

-- 대시보드는 publishable(anon) 키로 접속하므로 다른 테이블들과 같은 방식으로 열어둡니다.
drop policy if exists "public read access" on team_task_comments;
drop policy if exists "public insert access" on team_task_comments;
drop policy if exists "public update access" on team_task_comments;
drop policy if exists "public delete access" on team_task_comments;

create policy "public read access" on team_task_comments for select using (true);
create policy "public insert access" on team_task_comments for insert with check (true);
create policy "public update access" on team_task_comments for update using (true);
create policy "public delete access" on team_task_comments for delete using (true);

-- 확인 — 아래 결과가 1줄 나오면 성공입니다.
select table_name as "만들어진 테이블"
from information_schema.tables
where table_schema = 'public'
  and table_name = 'team_task_comments';
