-- 주간 업무 리포트를 담는 표입니다.
-- Supabase 프로젝트 대시보드 > SQL Editor 에 전체를 붙여넣고 Run 하세요.
--
-- 매주 금요일 19:10(KST)에 GitHub Actions가 scripts/weekly-task-report.js 를 돌려
-- 그 주(월~금)의 업무를 정리해 한 줄씩 넣습니다. 대시보드는 이 표만 읽습니다.
--   · summary : 완료율 요약 (전체/일자별/그룹별)
--   · special : 긴급 업무와 직접 추가한 업무
--   · notes   : 업무 목적과 댓글이 오간 업무
--
-- 같은 주를 다시 발행하면 덮어씁니다 (assignee + week_start 가 유일).

create table if not exists weekly_task_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  assignee text not null,
  week_start date not null,
  week_end date not null,
  total_count integer not null default 0,
  done_count integer not null default 0,
  summary jsonb,
  special jsonb,
  notes jsonb,
  unique (assignee, week_start)
);

create index if not exists weekly_task_reports_week_idx
  on weekly_task_reports (assignee, week_start desc);

alter table weekly_task_reports enable row level security;

drop policy if exists "public read access" on weekly_task_reports;
drop policy if exists "public insert access" on weekly_task_reports;
drop policy if exists "public update access" on weekly_task_reports;

create policy "public read access" on weekly_task_reports for select using (true);
create policy "public insert access" on weekly_task_reports for insert with check (true);
create policy "public update access" on weekly_task_reports for update using (true);

-- 확인 — 아래 결과가 1줄 나오면 성공입니다.
select table_name as "만들어진 표"
from information_schema.tables
where table_schema = 'public' and table_name = 'weekly_task_reports';
